server:
  port: 8082
spring:
  application:
    name: demo-01
  datasource:
    url: jdbc:mysql://47.102.122.186:3306/stock_analysis?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
